http://drupal.org/node/1675136
    Notice: Undefined index: #taxonomy_term in panelizer_entity_view_alter() (line 196 of /srv/bindings/5045af9776574f0da135c583b0fd0a74/code/profiles/pushtape/modules/contrib/panelizer/panelizer.module).
    EntityMalformedException: Missing bundle property on entity of type taxonomy_term. in entity_extract_ids() (line 7552 of /srv/bindings/5045af9776574f0da135c583b0fd0a74/code/includes/common.inc).