Reverting changes due to panopoly theme error.
Fatal error: require_once(): Failed opening required '/panopoly_theme.profile.inc' (include_path='.:/usr/share/pear:/usr/share/php') in /srv/bindings/05d020846a744725807ed2571ba7d33f/code/profiles/pushtape/pushtape.profile on line 9